/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#d4e3ff",
        "on-surface-variant": "#c5c4db",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#464747",
        "on-tertiary-fixed": "#001c39",
        "primary-fixed": "#e0e0ff",
        "secondary-container": "#464747",
        "on-error": "#690005",
        "outline-variant": "#454558",
        "primary": "#bec2ff",
        "background": "#131313",
        "tertiary-fixed-dim": "#a4c9ff",
        "inverse-surface": "#e5e2e1",
        "surface-bright": "#393939",
        "on-tertiary-container": "#92bfff",
        "error-container": "#93000a",
        "tertiary-container": "#004d8d",
        "on-primary-container": "#b3b7ff",
        "primary-container": "#0000ff",
        "surface": "#131313",
        "surface-dim": "#131313",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary": "#00315d",
        "on-primary": "#0001ac",
        "secondary-fixed-dim": "#c7c6c6",
        "surface-container": "#202020",
        "on-secondary-fixed": "#1a1c1c",
        "inverse-on-surface": "#303030",
        "primary-fixed-dim": "#bec2ff",
        "on-background": "#e5e2e1",
        "surface-container-highest": "#353535",
        "surface-tint": "#bec2ff",
        "on-surface": "#e5e2e1",
        "on-primary-fixed": "#00006e",
        "secondary": "#c7c6c6",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#2a2a2a",
        "tertiary": "#a4c9ff",
        "on-primary-fixed-variant": "#0000ef",
        "outline": "#8f8fa4",
        "on-secondary-container": "#b5b5b5",
        "on-secondary": "#2f3131",
        "surface-variant": "#353535",
        "on-tertiary-fixed-variant": "#004883",
        "surface-container-low": "#1b1c1c",
        "secondary-fixed": "#e3e2e2",
        "inverse-primary": "#343dff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
        "2xl": "1rem"
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["Geist Mono", "Menlo", "Monaco", "monospace"],
      },
    },
  },
  plugins: [],
};